/* Generated By:JavaCC: Do not edit this line. AdaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AdaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUOTATION = 5;
  /** RegularExpression Id. */
  int NUMBERSIGN = 6;
  /** RegularExpression Id. */
  int AMPERSAND = 7;
  /** RegularExpression Id. */
  int APOSTROPHE = 8;
  /** RegularExpression Id. */
  int LPARENTHESIS = 9;
  /** RegularExpression Id. */
  int RPARENTHESIS = 10;
  /** RegularExpression Id. */
  int ASTERISK = 11;
  /** RegularExpression Id. */
  int PLUS = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int HYPHEN = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int ATSIGN = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int SEMICOLON = 18;
  /** RegularExpression Id. */
  int LESSTHAN = 19;
  /** RegularExpression Id. */
  int EQUALS = 20;
  /** RegularExpression Id. */
  int GREATERTHAN = 21;
  /** RegularExpression Id. */
  int UNDERLINE = 22;
  /** RegularExpression Id. */
  int VERTICALLINE = 23;
  /** RegularExpression Id. */
  int SOLIDUS = 24;
  /** RegularExpression Id. */
  int EXCLAMATION = 25;
  /** RegularExpression Id. */
  int PERCENT = 26;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 27;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 28;
  /** RegularExpression Id. */
  int ABORT = 29;
  /** RegularExpression Id. */
  int ABS = 30;
  /** RegularExpression Id. */
  int ABSTRACT = 31;
  /** RegularExpression Id. */
  int ACCEPT = 32;
  /** RegularExpression Id. */
  int ACCESS = 33;
  /** RegularExpression Id. */
  int ALIASED = 34;
  /** RegularExpression Id. */
  int ALL = 35;
  /** RegularExpression Id. */
  int AND = 36;
  /** RegularExpression Id. */
  int ARRAY = 37;
  /** RegularExpression Id. */
  int AT = 38;
  /** RegularExpression Id. */
  int BEGIN = 39;
  /** RegularExpression Id. */
  int BODY = 40;
  /** RegularExpression Id. */
  int CASE = 41;
  /** RegularExpression Id. */
  int CONSTANT = 42;
  /** RegularExpression Id. */
  int DECLARE = 43;
  /** RegularExpression Id. */
  int DELAY = 44;
  /** RegularExpression Id. */
  int DELTA = 45;
  /** RegularExpression Id. */
  int DIGITS = 46;
  /** RegularExpression Id. */
  int DO = 47;
  /** RegularExpression Id. */
  int ELSE = 48;
  /** RegularExpression Id. */
  int ELSIF = 49;
  /** RegularExpression Id. */
  int END = 50;
  /** RegularExpression Id. */
  int ENTRY = 51;
  /** RegularExpression Id. */
  int EXCEPTION = 52;
  /** RegularExpression Id. */
  int EXIT = 53;
  /** RegularExpression Id. */
  int FOR = 54;
  /** RegularExpression Id. */
  int FUNCTION = 55;
  /** RegularExpression Id. */
  int GENERIC = 56;
  /** RegularExpression Id. */
  int GOTO = 57;
  /** RegularExpression Id. */
  int IF = 58;
  /** RegularExpression Id. */
  int IN = 59;
  /** RegularExpression Id. */
  int IS = 60;
  /** RegularExpression Id. */
  int LIMITED = 61;
  /** RegularExpression Id. */
  int LOOP = 62;
  /** RegularExpression Id. */
  int MOD = 63;
  /** RegularExpression Id. */
  int NEW = 64;
  /** RegularExpression Id. */
  int NOT = 65;
  /** RegularExpression Id. */
  int NULL = 66;
  /** RegularExpression Id. */
  int OF = 67;
  /** RegularExpression Id. */
  int OR = 68;
  /** RegularExpression Id. */
  int OTHERS = 69;
  /** RegularExpression Id. */
  int OUT = 70;
  /** RegularExpression Id. */
  int OVERRIDING = 71;
  /** RegularExpression Id. */
  int PACKAGE = 72;
  /** RegularExpression Id. */
  int PRAGMA = 73;
  /** RegularExpression Id. */
  int PRIVATE = 74;
  /** RegularExpression Id. */
  int PROCEDURE = 75;
  /** RegularExpression Id. */
  int PROTECTED = 76;
  /** RegularExpression Id. */
  int RAISE = 77;
  /** RegularExpression Id. */
  int RANGE = 78;
  /** RegularExpression Id. */
  int RECORD = 79;
  /** RegularExpression Id. */
  int REM = 80;
  /** RegularExpression Id. */
  int RETURN = 81;
  /** RegularExpression Id. */
  int REVERSE = 82;
  /** RegularExpression Id. */
  int SELECT = 83;
  /** RegularExpression Id. */
  int SEPARATE = 84;
  /** RegularExpression Id. */
  int SOME = 85;
  /** RegularExpression Id. */
  int SUBTYPE = 86;
  /** RegularExpression Id. */
  int TAGGED = 87;
  /** RegularExpression Id. */
  int TASK = 88;
  /** RegularExpression Id. */
  int TERMINATE = 89;
  /** RegularExpression Id. */
  int THEN = 90;
  /** RegularExpression Id. */
  int TYPE = 91;
  /** RegularExpression Id. */
  int UNTILL = 92;
  /** RegularExpression Id. */
  int USE = 93;
  /** RegularExpression Id. */
  int WHEN = 94;
  /** RegularExpression Id. */
  int WHILE = 95;
  /** RegularExpression Id. */
  int WITH = 96;
  /** RegularExpression Id. */
  int XOR = 97;
  /** RegularExpression Id. */
  int NUMBER = 98;
  /** RegularExpression Id. */
  int ID = 99;
  /** RegularExpression Id. */
  int a = 100;
  /** RegularExpression Id. */
  int b = 101;
  /** RegularExpression Id. */
  int c = 102;
  /** RegularExpression Id. */
  int d = 103;
  /** RegularExpression Id. */
  int e = 104;
  /** RegularExpression Id. */
  int f = 105;
  /** RegularExpression Id. */
  int g = 106;
  /** RegularExpression Id. */
  int h = 107;
  /** RegularExpression Id. */
  int i = 108;
  /** RegularExpression Id. */
  int j = 109;
  /** RegularExpression Id. */
  int k = 110;
  /** RegularExpression Id. */
  int l = 111;
  /** RegularExpression Id. */
  int m = 112;
  /** RegularExpression Id. */
  int n = 113;
  /** RegularExpression Id. */
  int o = 114;
  /** RegularExpression Id. */
  int p = 115;
  /** RegularExpression Id. */
  int q = 116;
  /** RegularExpression Id. */
  int r = 117;
  /** RegularExpression Id. */
  int s = 118;
  /** RegularExpression Id. */
  int t = 119;
  /** RegularExpression Id. */
  int u = 120;
  /** RegularExpression Id. */
  int v = 121;
  /** RegularExpression Id. */
  int w = 122;
  /** RegularExpression Id. */
  int x = 123;
  /** RegularExpression Id. */
  int y = 124;
  /** RegularExpression Id. */
  int z = 125;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\"\"",
    "\"#\"",
    "\"&\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\",\"",
    "\"-\"",
    "\".\"",
    "\"@\"",
    "\":\"",
    "\";\"",
    "\"<\"",
    "\"=\"",
    "\">\"",
    "\"_\"",
    "\"|\"",
    "\"/\"",
    "\"!\"",
    "\"%\"",
    "\"[\"",
    "\"]\"",
    "<ABORT>",
    "<ABS>",
    "<ABSTRACT>",
    "<ACCEPT>",
    "<ACCESS>",
    "<ALIASED>",
    "<ALL>",
    "<AND>",
    "<ARRAY>",
    "<AT>",
    "<BEGIN>",
    "<BODY>",
    "<CASE>",
    "<CONSTANT>",
    "<DECLARE>",
    "<DELAY>",
    "<DELTA>",
    "<DIGITS>",
    "<DO>",
    "<ELSE>",
    "<ELSIF>",
    "<END>",
    "<ENTRY>",
    "<EXCEPTION>",
    "<EXIT>",
    "<FOR>",
    "<FUNCTION>",
    "<GENERIC>",
    "<GOTO>",
    "<IF>",
    "<IN>",
    "<IS>",
    "<LIMITED>",
    "<LOOP>",
    "<MOD>",
    "<NEW>",
    "<NOT>",
    "<NULL>",
    "<OF>",
    "<OR>",
    "<OTHERS>",
    "<OUT>",
    "<OVERRIDING>",
    "<PACKAGE>",
    "<PRAGMA>",
    "<PRIVATE>",
    "<PROCEDURE>",
    "<PROTECTED>",
    "<RAISE>",
    "<RANGE>",
    "<RECORD>",
    "<REM>",
    "<RETURN>",
    "<REVERSE>",
    "<SELECT>",
    "<SEPARATE>",
    "<SOME>",
    "<SUBTYPE>",
    "<TAGGED>",
    "<TASK>",
    "<TERMINATE>",
    "<THEN>",
    "<TYPE>",
    "<UNTILL>",
    "<USE>",
    "<WHEN>",
    "<WHILE>",
    "<WITH>",
    "<XOR>",
    "<NUMBER>",
    "<ID>",
    "<a>",
    "<b>",
    "<c>",
    "<d>",
    "<e>",
    "<f>",
    "<g>",
    "<h>",
    "<i>",
    "<j>",
    "<k>",
    "<l>",
    "<m>",
    "<n>",
    "<o>",
    "<p>",
    "<q>",
    "<r>",
    "<s>",
    "<t>",
    "<u>",
    "<v>",
    "<w>",
    "<x>",
    "<y>",
    "<z>",
  };

}
